spring.application.name=producer
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/events_db
spring.datasource.username=admin
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none


spring.rabbitmq.addresses=amqps://cjxxkjdv:Q7R5XUFNaVxaAizgl-qx3vSSLCiaa_Hn@jaragua.lmq.cloudamqp.com/cjxxkjdv